
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver

server:
  port: 8081
